// Custom code: not generated by Stainless. See AGENTS.md.

package cdn_logs_uploader_target

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ validator.Object = authConfigValidator{}

// allowedAuthConfigFields maps each auth.config field to the set of auth.type
// values for which it is valid.
//
// The gcore-go SDK models auth.config as a discriminated union keyed on
// auth.type, but the Terraform schema flattens it into a single struct that
// exposes every field for every type. The API silently accepts fields that do
// not belong to the selected auth.type on create, but omits them on GET,
// producing perpetual plan drift (e.g. header_name set on a shared_key/sas_token
// Azure Blob or ak_sk SLS target). This validator rejects those fields at plan
// time instead.
//
// Mapping:
//   - token       -> token, header_name
//   - sas_token   -> token
//   - shared_key  -> account_key
//   - ak_sk       -> access_key_id, secret_access_key
var allowedAuthConfigFields = map[string]map[string]bool{
	"token":             {"token": true, "sas_token": true},
	"header_name":       {"token": true},
	"account_key":       {"shared_key": true},
	"access_key_id":     {"ak_sk": true},
	"secret_access_key": {"ak_sk": true},
}

// authConfigValidator validates that only the auth.config fields belonging to
// the selected auth.type are set. It is attached to the auth object so it can
// read both the type and its config siblings.
type authConfigValidator struct{}

func (authConfigValidator) Description(_ context.Context) string {
	return "validates that auth.config fields match the selected auth.type"
}

func (authConfigValidator) MarkdownDescription(_ context.Context) string {
	return "validates that auth.config fields match the selected auth.type"
}

func (authConfigValidator) ValidateObject(_ context.Context, req validator.ObjectRequest, resp *validator.ObjectResponse) {
	if req.ConfigValue.IsNull() || req.ConfigValue.IsUnknown() {
		return
	}

	attrs := req.ConfigValue.Attributes()

	typeVal, ok := attrs["type"].(types.String)
	if !ok || typeVal.IsNull() || typeVal.IsUnknown() {
		return
	}
	authType := strings.ToLower(typeVal.ValueString())

	cfg, ok := attrs["config"].(types.Object)
	if !ok || cfg.IsNull() || cfg.IsUnknown() {
		return
	}

	for name, v := range cfg.Attributes() {
		s, ok := v.(types.String)
		if !ok || s.IsNull() || s.IsUnknown() || s.ValueString() == "" {
			continue
		}
		allowed, tracked := allowedAuthConfigFields[name]
		if !tracked || allowed[authType] {
			continue
		}
		resp.Diagnostics.AddAttributeError(
			req.Path.AtName("config").AtName(name),
			"Invalid auth.config field for auth type",
			fmt.Sprintf("'%s' is not valid for auth type '%s'; remove it or change 'type'.", name, authType),
		)
	}
}
