package sweep

import (
	"log"
	"regexp"
	"strings"
)

// IsTestResource checks if a resource name matches test prefixes.
// This is the primary safety mechanism for sweepers - only resources
// with recognized test prefixes will be deleted.
//
// Recognized patterns:
// - Prefix-based: tf-test-*, tf_test_* (underscore variant)
// - Random names: 10-character alphanumeric strings (from acctest.RandomName)
//
// Returns true if the resource should be swept, false if it should be skipped.
func IsTestResource(name string) bool {
	// Standard test prefixes
	testPrefixes := []string{
		"tf-test", // Standard prefix (used by acctest.RandomName)
		"tf_test", // Underscore variant
	}

	// Check standard prefixes
	for _, prefix := range testPrefixes {
		if strings.HasPrefix(name, prefix) {
			return true
		}
	}

	// Match random 10-character strings generated by acctest.RandomName()
	// Example: "a1b2c3d4e5" from acctest.RandomName("") with custom seed
	randomPattern := regexp.MustCompile(`^[0-9A-Za-z]{10}$`)
	if randomPattern.MatchString(name) {
		return true
	}

	// Default: DO NOT sweep
	// When in doubt, preserve the resource
	return false
}

// ShouldSweep logs and returns whether a resource should be swept.
// This function combines the name check with logging for visibility
// during sweeper runs.
//
// Parameters:
//   - resourceType: The Terraform resource type (e.g., "gcore_cloud_volume")
//   - name: The resource name to check
//
// Returns true if the resource should be deleted, false otherwise.
func ShouldSweep(resourceType, name string) bool {
	if IsTestResource(name) {
		log.Printf("[INFO] Sweeping %s: %s", resourceType, name)
		return true
	}

	log.Printf("[DEBUG] Skipping %s: %s (not a test resource)", resourceType, name)
	return false
}

// SkipSweepError determines if a sweeper error should be skipped.
// Some errors are expected and shouldn't cause the entire sweep to fail.
//
// Common skippable errors:
// - Access denied (sweeper doesn't have permission)
// - Resource not found (already deleted)
// - Region not available (region doesn't exist for this account)
//
// Returns true if the error should be ignored, false if it's a real failure.
func SkipSweepError(err error) bool {
	if err == nil {
		return false
	}

	errMsg := err.Error()

	// Skip access denied errors
	skipPatterns := []string{
		"Access Denied",
		"AccessDenied",
		"Forbidden",
		"403",
		"UnauthorizedOperation",
		"not authorized",
		"insufficient permissions",
		// Add more patterns as needed based on Gcore API errors
	}

	for _, pattern := range skipPatterns {
		if strings.Contains(errMsg, pattern) {
			return true
		}
	}

	return false
}
