// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cloud_audit_log

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/stainless-sdks/gcore-terraform/internal/customfield"
)

var _ datasource.DataSourceWithConfigValidators = (*CloudAuditLogsDataSource)(nil)

func ListDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"from_timestamp": schema.StringAttribute{
				Description: "ISO formatted datetime string. Starting timestamp from which user actions are requested",
				Optional:    true,
				CustomType:  timetypes.RFC3339Type{},
			},
			"search_field": schema.StringAttribute{
				Description: "Extra search field for common object properties such as name, IP address, or other, depending on the `resource_type`",
				Optional:    true,
			},
			"to_timestamp": schema.StringAttribute{
				Description: "ISO formatted datetime string. Ending timestamp until which user actions are requested",
				Optional:    true,
				CustomType:  timetypes.RFC3339Type{},
			},
			"action_type": schema.ListAttribute{
				Description: "User action type. Several options can be specified.",
				Optional:    true,
				Validators: []validator.List{
					listvalidator.ValueStringsAre(
						stringvalidator.OneOfCaseInsensitive(
							"activate",
							"attach",
							"change_logging_resources",
							"create",
							"create_access_rule",
							"deactivate",
							"delete",
							"delete_access_rule",
							"delete_metadata",
							"detach",
							"disable_logging",
							"disable_portsecurity",
							"download",
							"enable_logging",
							"enable_portsecurity",
							"failover",
							"put_into_servergroup",
							"reboot",
							"reboot_hard",
							"rebuild",
							"regenerate_credentials",
							"remove_from_servergroup",
							"replace_metadata",
							"resize",
							"resume",
							"retype",
							"revert",
							"scale_down",
							"scale_up",
							"start",
							"stop",
							"suspend",
							"update",
							"update_metadata",
							"upgrade",
						),
					),
				},
				ElementType: types.StringType,
			},
			"api_group": schema.ListAttribute{
				Description: "API group that requested action belongs to. Several options can be specified.",
				Optional:    true,
				Validators: []validator.List{
					listvalidator.ValueStringsAre(
						stringvalidator.OneOfCaseInsensitive(
							"ai_cluster",
							"backup_service",
							"caas_container",
							"caas_key",
							"caas_pull_secret",
							"dbaas_postgres",
							"ddos_profile",
							"faas_function",
							"faas_key",
							"faas_namespace",
							"file_shares",
							"floating_ip",
							"image",
							"inference_at_the_edge",
							"instance",
							"instance_isolation",
							"k8s_cluster",
							"k8s_cluster_template",
							"k8s_pool",
							"laas",
							"laas_topic",
							"lb_health_monitor",
							"lb_l7policy",
							"lb_l7rule",
							"lblistener",
							"lbpool",
							"lbpool_member",
							"lifecycle_policy",
							"lifecycle_policy_volume_member",
							"loadbalancer",
							"network",
							"port",
							"project",
							"quota_limit_request",
							"registry",
							"reservation",
							"reserved_fixed_ip",
							"role",
							"router",
							"secret",
							"securitygroup",
							"securitygrouprule",
							"servergroup",
							"shared_flavor",
							"shared_image",
							"shared_network",
							"snapshot",
							"snapshot_schedule",
							"ssh_key",
							"subnet",
							"user",
							"vip_ip_addresses",
							"volume",
						),
					),
				},
				ElementType: types.StringType,
			},
			"project_id": schema.ListAttribute{
				Description: "Project ID. Several options can be specified.",
				Optional:    true,
				ElementType: types.Int64Type,
			},
			"region_id": schema.ListAttribute{
				Description: "Region ID. Several options can be specified.",
				Optional:    true,
				ElementType: types.Int64Type,
			},
			"resource_id": schema.ListAttribute{
				Description: "Resource ID. Several options can be specified.",
				Optional:    true,
				ElementType: types.StringType,
			},
			"limit": schema.Int64Attribute{
				Description: "Optional. Limit the number of returned items",
				Computed:    true,
				Optional:    true,
				Validators: []validator.Int64{
					int64validator.AtMost(1000),
				},
			},
			"order_by": schema.StringAttribute{
				Description: "Sorting by timestamp. Oldest first, or most recent first\nAvailable values: \"asc\", \"desc\".",
				Computed:    true,
				Optional:    true,
				Validators: []validator.String{
					stringvalidator.OneOfCaseInsensitive("asc", "desc"),
				},
			},
			"sorting": schema.StringAttribute{
				Description:        "(DEPRECATED Use '`order_by`' instead) Sorting by timestamp. Oldest first, or most recent first\nAvailable values: \"asc\", \"desc\".",
				Computed:           true,
				Optional:           true,
				DeprecationMessage: "This attribute is deprecated.",
				Validators: []validator.String{
					stringvalidator.OneOfCaseInsensitive("asc", "desc"),
				},
			},
			"max_items": schema.Int64Attribute{
				Description: "Max items to fetch, default: 1000",
				Optional:    true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
			"items": schema.ListNestedAttribute{
				Description: "The items returned by the data source",
				Computed:    true,
				CustomType:  customfield.NewNestedObjectListType[CloudAuditLogsItemsDataSourceModel](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description: "User action ID",
							Computed:    true,
						},
						"acknowledged": schema.BoolAttribute{
							Description: "User action log was successfully received by its subscriber in case there is one",
							Computed:    true,
						},
						"action_data": schema.StringAttribute{
							Description: "Additional information about the action",
							Computed:    true,
							CustomType:  jsontypes.NormalizedType{},
						},
						"action_type": schema.StringAttribute{
							Description: "Action type\nAvailable values: \"activate\", \"attach\", \"change_logging_resources\", \"create\", \"create_access_rule\", \"deactivate\", \"delete\", \"delete_access_rule\", \"delete_metadata\", \"detach\", \"disable_logging\", \"disable_portsecurity\", \"download\", \"enable_logging\", \"enable_portsecurity\", \"failover\", \"put_into_servergroup\", \"reboot\", \"reboot_hard\", \"rebuild\", \"regenerate_credentials\", \"remove_from_servergroup\", \"replace_metadata\", \"resize\", \"resume\", \"retype\", \"revert\", \"scale_down\", \"scale_up\", \"start\", \"stop\", \"suspend\", \"update\", \"update_metadata\", \"upgrade\".",
							Computed:    true,
							Validators: []validator.String{
								stringvalidator.OneOfCaseInsensitive(
									"activate",
									"attach",
									"change_logging_resources",
									"create",
									"create_access_rule",
									"deactivate",
									"delete",
									"delete_access_rule",
									"delete_metadata",
									"detach",
									"disable_logging",
									"disable_portsecurity",
									"download",
									"enable_logging",
									"enable_portsecurity",
									"failover",
									"put_into_servergroup",
									"reboot",
									"reboot_hard",
									"rebuild",
									"regenerate_credentials",
									"remove_from_servergroup",
									"replace_metadata",
									"resize",
									"resume",
									"retype",
									"revert",
									"scale_down",
									"scale_up",
									"start",
									"stop",
									"suspend",
									"update",
									"update_metadata",
									"upgrade",
								),
							},
						},
						"api_group": schema.StringAttribute{
							Description: "API group\nAvailable values: \"ai_cluster\", \"backup_service\", \"caas_container\", \"caas_key\", \"caas_pull_secret\", \"dbaas_postgres\", \"ddos_profile\", \"faas_function\", \"faas_key\", \"faas_namespace\", \"file_shares\", \"floating_ip\", \"image\", \"inference_at_the_edge\", \"instance\", \"instance_isolation\", \"k8s_cluster\", \"k8s_cluster_template\", \"k8s_pool\", \"laas\", \"laas_topic\", \"lb_health_monitor\", \"lb_l7policy\", \"lb_l7rule\", \"lblistener\", \"lbpool\", \"lbpool_member\", \"lifecycle_policy\", \"lifecycle_policy_volume_member\", \"loadbalancer\", \"network\", \"port\", \"project\", \"quota_limit_request\", \"registry\", \"reservation\", \"reserved_fixed_ip\", \"role\", \"router\", \"secret\", \"securitygroup\", \"securitygrouprule\", \"servergroup\", \"shared_flavor\", \"shared_image\", \"shared_network\", \"snapshot\", \"snapshot_schedule\", \"ssh_key\", \"subnet\", \"user\", \"vip_ip_addresses\", \"volume\".",
							Computed:    true,
							Validators: []validator.String{
								stringvalidator.OneOfCaseInsensitive(
									"ai_cluster",
									"backup_service",
									"caas_container",
									"caas_key",
									"caas_pull_secret",
									"dbaas_postgres",
									"ddos_profile",
									"faas_function",
									"faas_key",
									"faas_namespace",
									"file_shares",
									"floating_ip",
									"image",
									"inference_at_the_edge",
									"instance",
									"instance_isolation",
									"k8s_cluster",
									"k8s_cluster_template",
									"k8s_pool",
									"laas",
									"laas_topic",
									"lb_health_monitor",
									"lb_l7policy",
									"lb_l7rule",
									"lblistener",
									"lbpool",
									"lbpool_member",
									"lifecycle_policy",
									"lifecycle_policy_volume_member",
									"loadbalancer",
									"network",
									"port",
									"project",
									"quota_limit_request",
									"registry",
									"reservation",
									"reserved_fixed_ip",
									"role",
									"router",
									"secret",
									"securitygroup",
									"securitygrouprule",
									"servergroup",
									"shared_flavor",
									"shared_image",
									"shared_network",
									"snapshot",
									"snapshot_schedule",
									"ssh_key",
									"subnet",
									"user",
									"vip_ip_addresses",
									"volume",
								),
							},
						},
						"client_id": schema.Int64Attribute{
							Description: "Client ID of the user.",
							Computed:    true,
						},
						"email": schema.StringAttribute{
							Description: "User email address",
							Computed:    true,
						},
						"is_complete": schema.BoolAttribute{
							Description: "User action was filled with all necessary information. If false, then something went wrong during user action creation or update",
							Computed:    true,
						},
						"issued_by_user_id": schema.Int64Attribute{
							Description: "User ID who issued the token that made the request",
							Computed:    true,
						},
						"project_id": schema.Int64Attribute{
							Description: "Project ID",
							Computed:    true,
						},
						"region_id": schema.Int64Attribute{
							Description: "Region ID",
							Computed:    true,
						},
						"resources": schema.ListNestedAttribute{
							Description: "Resources",
							Computed:    true,
							CustomType:  customfield.NewNestedObjectListType[CloudAuditLogsResourcesDataSourceModel](ctx),
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"resource_id": schema.StringAttribute{
										Description: "Resource ID",
										Computed:    true,
									},
									"resource_type": schema.StringAttribute{
										Description: "Resource type\nAvailable values: \"caas_container\", \"caas_key\", \"caas_pull_secret\", \"dbaas_postgres\", \"ddos_profile\", \"external_ip\", \"faas_function\", \"faas_key\", \"faas_namespace\", \"file_shares\", \"floating_ip\", \"gpu_baremetal_server\", \"gpu_virtual_server\", \"gpuai_cluster\", \"image\", \"inference_api_key\", \"inference_application\", \"inference_instance\", \"inference_registry_credentials\", \"inference_secret\", \"instance\", \"ipu_cluster\", \"k8s_cluster\", \"k8s_cluster_template\", \"k8s_pool\", \"laas\", \"laas_topic\", \"lb_health_monitor\", \"lb_l7policy\", \"lb_l7rule\", \"lblistener\", \"lbpool\", \"lbpool_member\", \"lifecycle_policy\", \"lifecycle_policy_volume_member\", \"loadbalancer\", \"network\", \"port\", \"project\", \"quota_limit_request\", \"registry\", \"registry_repository\", \"registry_repository_artifact\", \"registry_repository_tag\", \"registry_user\", \"registry_user_sercret\", \"reservation\", \"role\", \"router\", \"secret\", \"securitygroup\", \"securitygrouprule\", \"servergroup\", \"shared_flavor\", \"shared_image\", \"shared_network\", \"snapshot\", \"snapshot_schedule\", \"ssh_key\", \"subnet\", \"token\", \"user\", \"virtual_gpu_cluster\", \"volume\".",
										Computed:    true,
										Validators: []validator.String{
											stringvalidator.OneOfCaseInsensitive(
												"caas_container",
												"caas_key",
												"caas_pull_secret",
												"dbaas_postgres",
												"ddos_profile",
												"external_ip",
												"faas_function",
												"faas_key",
												"faas_namespace",
												"file_shares",
												"floating_ip",
												"gpu_baremetal_server",
												"gpu_virtual_server",
												"gpuai_cluster",
												"image",
												"inference_api_key",
												"inference_application",
												"inference_instance",
												"inference_registry_credentials",
												"inference_secret",
												"instance",
												"ipu_cluster",
												"k8s_cluster",
												"k8s_cluster_template",
												"k8s_pool",
												"laas",
												"laas_topic",
												"lb_health_monitor",
												"lb_l7policy",
												"lb_l7rule",
												"lblistener",
												"lbpool",
												"lbpool_member",
												"lifecycle_policy",
												"lifecycle_policy_volume_member",
												"loadbalancer",
												"network",
												"port",
												"project",
												"quota_limit_request",
												"registry",
												"registry_repository",
												"registry_repository_artifact",
												"registry_repository_tag",
												"registry_user",
												"registry_user_sercret",
												"reservation",
												"role",
												"router",
												"secret",
												"securitygroup",
												"securitygrouprule",
												"servergroup",
												"shared_flavor",
												"shared_image",
												"shared_network",
												"snapshot",
												"snapshot_schedule",
												"ssh_key",
												"subnet",
												"token",
												"user",
												"virtual_gpu_cluster",
												"volume",
											),
										},
									},
									"resource_body": schema.StringAttribute{
										Description: "Free-form object, resource body.",
										Computed:    true,
										CustomType:  jsontypes.NormalizedType{},
									},
									"search_field": schema.StringAttribute{
										Description: "Often used property for filtering actions. It can be a name, IP address, or other property, depending on the `resource_type`",
										Computed:    true,
									},
								},
							},
						},
						"task_id": schema.StringAttribute{
							Description: "Task ID",
							Computed:    true,
						},
						"timestamp": schema.StringAttribute{
							Description: "Datetime. Action timestamp",
							Computed:    true,
							CustomType:  timetypes.RFC3339Type{},
						},
						"token_id": schema.Int64Attribute{
							Description: "Token ID",
							Computed:    true,
						},
						"total_price": schema.SingleNestedAttribute{
							Description: "Total resource price VAT inclusive",
							Computed:    true,
							CustomType:  customfield.NewNestedObjectType[CloudAuditLogsTotalPriceDataSourceModel](ctx),
							Attributes: map[string]schema.Attribute{
								"currency_code": schema.StringAttribute{
									Description: "Currency code (3 letter code per ISO 4217)",
									Computed:    true,
								},
								"price_per_hour": schema.Float64Attribute{
									Description: "Total price VAT inclusive per hour",
									Computed:    true,
								},
								"price_per_month": schema.Float64Attribute{
									Description: "Total price VAT inclusive per month (30 days)",
									Computed:    true,
								},
								"price_status": schema.StringAttribute{
									Description: "Price status for the UI\nAvailable values: \"error\", \"hide\", \"show\".",
									Computed:    true,
									Validators: []validator.String{
										stringvalidator.OneOfCaseInsensitive(
											"error",
											"hide",
											"show",
										),
									},
								},
							},
						},
						"user_id": schema.Int64Attribute{
							Description: "User ID",
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func (d *CloudAuditLogsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = ListDataSourceSchema(ctx)
}

func (d *CloudAuditLogsDataSource) ConfigValidators(_ context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{}
}
