#!/usr/bin/env bash

set -e

cd -- "$(dirname -- "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/G-Core/gcore-go,github.com/stainless-sdks/gcore-go"

echo "==> Generating Terraform provider documentation"

EXEC='tfplugindocs'
if ! command -v -- "$EXEC" &> /dev/null; then
  go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs
  EXEC="$(go env -- GOPATH)/bin/$EXEC"
fi

case "$OSTYPE" in
linux*)
  export -- TMPDIR=/var/tmp
  ;;
*) ;;
esac

go mod tidy -e
exec -- "$EXEC" generate -rendered-provider-name "Gcore" -provider-name="gcore"
