#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/G-Core/gcore-go,github.com/stainless-sdks/gcore-go"

REPLACEMENT="${1:-"../gcore-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/G-Core/gcore-go="$REPLACEMENT"
go mod tidy -e
