// This file is not generated by Stainless and is preserved across codegen runs.
// It covers the two pool member data sources against the API; only schema and
// model parity are generated (GCLOUD2-27021).

package cloud_load_balancer_pool_member_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/compare"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"

	"github.com/G-Core/terraform-provider-gcore/internal/acctest"
)

// The singular data source must agree with the resource it read.
func TestAccCloudLoadBalancerPoolMemberDataSource_basic(t *testing.T) {
	rName := acctest.RandomName()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCloudLoadBalancerPoolMemberDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCloudLoadBalancerPoolMemberDataSourceConfig(rName),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.CompareValuePairs(
						"gcore_cloud_load_balancer_pool_member.test", tfjsonpath.New("id"),
						"data.gcore_cloud_load_balancer_pool_member.test", tfjsonpath.New("id"),
						compare.ValuesSame(),
					),
					statecheck.CompareValuePairs(
						"gcore_cloud_load_balancer_pool_member.test", tfjsonpath.New("address"),
						"data.gcore_cloud_load_balancer_pool_member.test", tfjsonpath.New("address"),
						compare.ValuesSame(),
					),
					statecheck.CompareValuePairs(
						"gcore_cloud_load_balancer_pool_member.test", tfjsonpath.New("protocol_port"),
						"data.gcore_cloud_load_balancer_pool_member.test", tfjsonpath.New("protocol_port"),
						compare.ValuesSame(),
					),
					statecheck.ExpectKnownValue("data.gcore_cloud_load_balancer_pool_member.test",
						tfjsonpath.New("operating_status"), knownvalue.NotNull()),
					statecheck.ExpectKnownValue("data.gcore_cloud_load_balancer_pool_member.test",
						tfjsonpath.New("provisioning_status"), knownvalue.NotNull()),
					statecheck.ExpectKnownValue("data.gcore_cloud_load_balancer_pool_member.test",
						tfjsonpath.New("weight"), knownvalue.Int64Exact(3)),
				},
			},
		},
	})
}

// The list data source must return both members of the pool.
func TestAccCloudLoadBalancerPoolMembersDataSource_basic(t *testing.T) {
	rName := acctest.RandomName()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCloudLoadBalancerPoolMemberDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCloudLoadBalancerPoolMembersDataSourceConfig(rName),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue("data.gcore_cloud_load_balancer_pool_members.test",
						tfjsonpath.New("items"), knownvalue.ListSizeExact(2)),
					statecheck.ExpectKnownValue("data.gcore_cloud_load_balancer_pool_members.test",
						tfjsonpath.New("items").AtSliceIndex(0).AtMapKey("id"), knownvalue.NotNull()),
					statecheck.ExpectKnownValue("data.gcore_cloud_load_balancer_pool_members.test",
						tfjsonpath.New("items").AtSliceIndex(0).AtMapKey("address"), knownvalue.NotNull()),
				},
			},
		},
	})
}

func testAccCloudLoadBalancerPoolMemberDataSourceConfig(name string) string {
	return fmt.Sprintf(`
resource "gcore_cloud_load_balancer" "test" {
  project_id = %[1]s
  region_id  = %[2]s
  name       = "%[3]s-lb"
  flavor     = "lb1-1-2"
}

resource "gcore_cloud_load_balancer_pool" "test" {
  project_id       = %[1]s
  region_id        = %[2]s
  name             = "%[3]s-pool"
  lb_algorithm     = "ROUND_ROBIN"
  protocol         = "HTTP"
  load_balancer_id = gcore_cloud_load_balancer.test.id
}

resource "gcore_cloud_load_balancer_pool_member" "test" {
  project_id    = %[1]s
  region_id     = %[2]s
  pool_id       = gcore_cloud_load_balancer_pool.test.id
  address       = "192.168.1.60"
  protocol_port = 80
  weight        = 3
}

data "gcore_cloud_load_balancer_pool_member" "test" {
  project_id = %[1]s
  region_id  = %[2]s
  pool_id    = gcore_cloud_load_balancer_pool.test.id
  member_id  = gcore_cloud_load_balancer_pool_member.test.id
}`, acctest.ProjectID(), acctest.RegionID(), name)
}

func testAccCloudLoadBalancerPoolMembersDataSourceConfig(name string) string {
	return fmt.Sprintf(`
resource "gcore_cloud_load_balancer" "test" {
  project_id = %[1]s
  region_id  = %[2]s
  name       = "%[3]s-lb"
  flavor     = "lb1-1-2"
}

resource "gcore_cloud_load_balancer_pool" "test" {
  project_id       = %[1]s
  region_id        = %[2]s
  name             = "%[3]s-pool"
  lb_algorithm     = "ROUND_ROBIN"
  protocol         = "HTTP"
  load_balancer_id = gcore_cloud_load_balancer.test.id
}

resource "gcore_cloud_load_balancer_pool_member" "first" {
  project_id    = %[1]s
  region_id     = %[2]s
  pool_id       = gcore_cloud_load_balancer_pool.test.id
  address       = "192.168.1.61"
  protocol_port = 80
}

resource "gcore_cloud_load_balancer_pool_member" "second" {
  project_id    = %[1]s
  region_id     = %[2]s
  pool_id       = gcore_cloud_load_balancer_pool.test.id
  address       = "192.168.1.62"
  protocol_port = 80

  # The pool holds a task lock per member write, so serialise the two creates.
  depends_on = [gcore_cloud_load_balancer_pool_member.first]
}

data "gcore_cloud_load_balancer_pool_members" "test" {
  project_id = %[1]s
  region_id  = %[2]s
  pool_id    = gcore_cloud_load_balancer_pool.test.id

  depends_on = [
    gcore_cloud_load_balancer_pool_member.first,
    gcore_cloud_load_balancer_pool_member.second,
  ]
}`, acctest.ProjectID(), acctest.RegionID(), name)
}
